FILE main.obj
FILE check.obj
FILE crossref.obj
FILE database.obj
FILE entry.obj
FILE error.obj
FILE expand.obj
FILE init.obj
FILE io.obj
FILE key.obj
FILE macros.obj
FILE names.obj
FILE parse.obj
FILE print.obj
FILE pxfile.obj
FILE record.obj
FILE rewrite.obj
FILE rsc.obj
FILE s_parse.obj
FILE symbols.obj
FILE stack.obj
FILE sbuffer.obj
FILE tex_aux.obj
FILE tex_read.obj
FILE type.obj
FILE version.obj
FILE wordlist.obj
FILE regex.obj
